apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: shahmeer138/springboot-app:latest
          ports:
            - containerPort: 9090
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/appdb
            - name: SPRING_DATASOURCE_USERNAME
              value: appuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: apppass