spring:
  datasource:
    url: jdbc:postgresql://my-postgres-postgresql:5432/backenddb
    username: postgres
    password: 75c2hn2wcj
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
server:
  port: 9090
  address: 0.0.0.0
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    metrics:
      enabled: true
  metrics:
    export:
      simple:
        enabled: true